project_id = "lobobranco-458901"
region     = "us-central1"
service_account = "data-pipeline-sa@lobobranco-458901.iam.gserviceaccount.com"
location     = "us"
dataset_id = "dataset_project"
table_id = "produtos"
image_version = "composer-3-airflow-2.9.3" 
environment_size = "ENVIRONMENT_SIZE_SMALL"